
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.11.0.3
//   Input filename:  Service.bond
//   Output filename: Service_grpc.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion


namespace GrpcInterceptorExample.Contracts
{
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.11.0.3")]
    public static class ExampleService 
    {
        static readonly string ServiceName = "GrpcInterceptorExample.Contracts.ExampleService";

        static readonly global::Grpc.Core.Method<global::Bond.Grpc.IMessage<SampleRequest>, global::Bond.Grpc.IMessage<SampleResponse>> Method_GetValue = new global::Grpc.Core.Method<global::Bond.Grpc.IMessage<SampleRequest>, global::Bond.Grpc.IMessage<SampleResponse>>(
            global::Grpc.Core.MethodType.Unary,
            ServiceName,
            "GetValue",
            global::Bond.Grpc.Marshaller<SampleRequest>.Instance,
            global::Bond.Grpc.Marshaller<SampleResponse>.Instance);

        public abstract class ExampleServiceBase
        {
            public abstract global::System.Threading.Tasks.Task<global::Bond.Grpc.IMessage<SampleResponse>> GetValue(global::Bond.Grpc.IMessage<SampleRequest> request, global::Grpc.Core.ServerCallContext context);
        }

        public class ExampleServiceClient : global::Grpc.Core.ClientBase<ExampleServiceClient>
        {
            public ExampleServiceClient(global::Grpc.Core.Channel channel) : base(channel)
            {
            }

            public ExampleServiceClient(global::Grpc.Core.CallInvoker callInvoker) : base(callInvoker)
            {
            }

            protected ExampleServiceClient() : base()
            {
            }

            protected ExampleServiceClient(global::Grpc.Core.ClientBase.ClientBaseConfiguration configuration) : base(configuration)
            {
            }

            public virtual global::Grpc.Core.AsyncUnaryCall<global::Bond.Grpc.IMessage<SampleResponse>> GetValueAsync(SampleRequest request, global::Grpc.Core.Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return GetValueAsync(global::Bond.Grpc.Message.From(request), new global::Grpc.Core.CallOptions(headers, deadline, cancellationToken));
            }

            public virtual global::Grpc.Core.AsyncUnaryCall<global::Bond.Grpc.IMessage<SampleResponse>> GetValueAsync(global::Bond.Grpc.IMessage<SampleRequest> request, global::Grpc.Core.CallOptions options)
            {
                return CallInvoker.AsyncUnaryCall(Method_GetValue, null, options, request);
            }

            protected override ExampleServiceClient NewInstance(global::Grpc.Core.ClientBase.ClientBaseConfiguration configuration)
            {
                return new ExampleServiceClient(configuration);
            }
        }

        public static global::Grpc.Core.ServerServiceDefinition BindService(ExampleServiceBase serviceImpl)
        {
            return global::Grpc.Core.ServerServiceDefinition.CreateBuilder()
                    .AddMethod(Method_GetValue, serviceImpl.GetValue)
                    .Build();
        }
    }

} // GrpcInterceptorExample.Contracts
